### ISSUE TITLE
Bubbling on focus event not working

### ISSUE THREAD

**Issue by igorsantos07** [timjansen/minified.js#41]
I'm trying to implement `.on('focus') to add some behaviour to newly created fields in a form. However, looks like bubbling is not working there.

An example is opening my [production app](http://gc.igorsantos.com.br) and running the following code in the console:  

won't show up: `$('form').on('focus', function() { console.log('bubbled') }, 'input[name=name]');`
will show up: `$('form input[name=name]').on('focus', function() { console.log('bubbled') });`

Am I doing something very stupidly wrong?

**Comment by timjansen** [comment]
Should have been fixed with 1.0 already (just cleaning up old issues).
