### ISSUE TITLE
Add onError handler for promises

### ISSUE THREAD

**Issue by aldendaniels** [timjansen/minified.js#48]
Both [RSVP](https://github.com/tildeio/rsvp.js/) and [Bluebird](https://github.com/petkaantonov/bluebird) support a global **on error** that is called whenever there appears to be an uncaught exception within a promise.

This is crucial - without this option, errors are silently swallowed when the developer fails to add an `.error()` handler. Worse, right now there's literally no way to detect an error that occurs in the final `.error()` handler on the promise chain.

Read @petkaantonov's excellent documentation about how errors should be handled in promises: https://github.com/petkaantonov/bluebird#error-handling

**Comment by timjansen** [comment]
Minified 1.1 will re-throw (unhandled) exception to the callng thread. Nia also has global error handlers now.
