### ISSUE TITLE
Request Success Codes

### ISSUE THREAD

**Issue by mariussmit** [timjansen/minified.js#51]
We use MinifiedJS in our framework because it is small and does what we need (templating, formatting, etc.) without having to include a whole lot of other libs. Our REST services return the HTTP codes depending on the action e.g. 200 = success and 201 = created. Minified throws an error though for anything other than 200 which isn't desired `xhr.status == 200`. We've updated our local copy to accept all 200 codes.
Do you plan to add this check? I see that nia also only checks for 200.

**Comment by timjansen** [comment]
Implemented this in Minified for 1.1.
