### ISSUE TITLE
.request async

### ISSUE THREAD

**Issue by lefedor** [timjansen/minified.js#53]
Hello, please add to .request settings ability to pass async mode key:

			var async = ('async' in settings)? settings['async']:true
			//xhr['open'](method, url, true, settings['user'], settings['pass']);
			xhr['open'](method, url, async, settings['user'], settings['pass']);

**Comment by timjansen** [comment]
Why do you need this? Synchronous mode is deprecated in FF30, possibly
other browsers as well.

Tim

**Comment by lefedor** [comment]
Hello, if it's will be deprecated, I'll better change my code, thanks for the hint.
I've needed it because of I'm changing old code to work with minified.
