### ISSUE TITLE
Minified.js can't live inline

### ISSUE THREAD

**Issue by grobmeier** [timjansen/minified.js#62]
Hi,

using Jekyll, I did the following:
```
<script type="text/javascript">{% include minified.js %}</script>
```

The source code of my page shows, minified was actually included (without any further transformation).

However, the page causes an error:

```
Uncaught SyntaxError: missing ) after argument list
```

To avoid this, I am forced to load minified like usual:

```
<script type="text/javascript" src="js/minified.js"></script>
```

I have several reasons for inlining minified, like Google PageSpeed, avoiding caching problems and so on.

I found it very surprising this didn't work - anything i can help with, please let me know.

Thanks!

**Comment by grobmeier** [comment]
I am very sorry, please ignore this issue.

The problem was Jekyll which I use. It uses Liquid, which also uses {{}} for templating things. This brought up a conflict with the MinifiedJS templating features.

Including minified with enclosing raw tags solved the issue for me:

```
// Using gulp and gulp-insert
.pipe(insert.wrap('{% raw %}', '{% endraw %}'))
```

**Comment by timjansen** [comment]
No worries, I am pretty busy this week and didn't have time to look into it
yet.

Tim
